name: invoice_app_sih
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cloud_firestore: ^4.9.1
  connectivity_plus: ^4.0.2
  email_validator: ^2.1.17
  file: ^6.1.4
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  get: ^4.6.5
  google_sign_in: ^6.1.5
  image_picker: ^0.8.5+3
  open_file: ^3.2.1
  path_provider: ^2.0.11
  pdf: ^3.8.1
  printing: ^5.9.1
  share_plus: ^4.0.10+1
  shared_preferences: ^2.0.15
  uuid: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
