name: invoice_app_sih
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pdf: ^3.8.1
  path_provider: ^2.0.11
  open_file: ^3.2.1
  printing: ^5.9.1
  image_picker: ^0.8.5+3
  file: ^6.1.4
  get: ^4.6.5
  share_plus: ^4.0.10+1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
